# Waldhütte Remetschwil: real terrain and layout, generated by tools/build_map.py from swissALTI3D, OSM and the
# swissimage aerial photo into assets/map/ (heightmap.f32 1 m grid, ground.png cover weights, map.json layout).
# Coordinates: +X = east, +Z = south, origin = Feuerstelle, heights relative to the fire (659 m a.s.l.).
class_name Map

const DIR := "res://assets/map/"

static var _loaded := false
static var _d: Dictionary = {}
static var _h: PackedFloat32Array
static var _ground: Image
static var _x0 := 0.0
static var _z0 := 0.0
static var _w := 1
static var _hh := 1
static var _sk: PackedFloat32Array
static var _skx0 := 0.0
static var _skz0 := 0.0
static var _skw := 1
static var _skh := 1
static var _skc := 10.0

static var ROADS: Array = []
static var BUILDINGS: Dictionary = {}
static var CLEARING: PackedVector2Array
static var FIRE := Vector2.ZERO
static var BENCHES: Array = []
static var SMALL_CAMPSITE: Dictionary = {}
static var TABLE := Vector3.ZERO          # x, z, yaw degrees
static var FOUNTAIN := Vector3.ZERO
static var POND: Dictionary = {}          # pos (Vector2), r, depth, water_y, trough (Vector2)
static var BIN := Vector2.ZERO
static var SIGNPOST := Vector2.ZERO
static var LOG_SEAT := Vector3.ZERO
static var LANDMARK_OAK := Vector2.ZERO
static var FENCE: Array = []
static var TREES: Array = []               # [x, z, kind, scale, yaw_deg]
static var SHRUBS: Array = []              # [x, z, scale, yaw_deg]
static var BORDER_TREES: Array = []        # outside the extent, visual only
static var VILLAGE: Array = []             # OSM building footprints outside the extent, backdrop
static var FERNS: Array = []
static var LOGS: Array = []
static var PLAYER_START := Vector2.ZERO
static var BOUNDS := Rect2()
static var BARRICADES: Array = []
static var SPAWNS: Dictionary = {}

static func _ensure() -> void:
	if _loaded:
		return
	_loaded = true
	_d = JSON.parse_string(FileAccess.get_file_as_string(DIR + "map.json"))
	_x0 = _d["x0"]; _z0 = _d["z0"]; _w = int(_d["w"]); _hh = int(_d["h"])
	_h = FileAccess.get_file_as_bytes(DIR + "heightmap.f32").to_float32_array()
	var sk: Dictionary = _d["skirt"]
	_skx0 = sk["x0"]; _skz0 = sk["z0"]; _skw = int(sk["w"]); _skh = int(sk["h"]); _skc = sk["cell"]
	_sk = FileAccess.get_file_as_bytes(DIR + "skirt.f32").to_float32_array()
	# Resource loading also works from an exported PCK, where PNGs are remapped.
	var ground_texture: Texture2D = load(DIR + "ground.png")
	_ground = ground_texture.get_image()
	if _ground.is_compressed():
		_ground.decompress()
	for r in _d["roads"]:
		var pts: Array = []
		for p in r["pts"]:
			pts.append(Vector2(p[0], p[1]))
		ROADS.append({ "name": r["name"], "surface": r["surface"], "width": float(r["width"]), "pts": pts })
	for k in _d["buildings"]:
		var b: Dictionary = _d["buildings"][k]
		BUILDINGS[k] = { "pos": Vector2(b["pos"][0], b["pos"][1]), "size": Vector2(b["size"][0], b["size"][1]),
			"yaw": -deg_to_rad(b["yaw_deg"]), "base_h": float(b["base_h"]), "wall_h": float(b["wall_h"]), "roof_h": float(b["roof_h"]) }
	for p in _d["clearing"]:
		CLEARING.append(Vector2(p[0], p[1]))
	FIRE = Vector2(_d["fire"][0], _d["fire"][1])
	for b in _d["benches"]:
		BENCHES.append([Vector2(b[0], b[1]), -deg_to_rad(b[2])])
	if _d.has("small_campsite"):
		var site: Dictionary = _d["small_campsite"]
		var seats: Array = []
		for b in site["benches"]:
			seats.append([Vector2(b[0], b[1]), -deg_to_rad(b[2])])
		SMALL_CAMPSITE = {"pos": Vector2(site["pos"][0], site["pos"][1]), "radius": float(site["radius"]), "benches": seats}
	TABLE = Vector3(_d["table"][0], _d["table"][1], -deg_to_rad(_d["table"][2]))
	FOUNTAIN = Vector3(_d["fountain"][0], _d["fountain"][1], -deg_to_rad(_d["fountain"][2]))
	BIN = Vector2(_d["bin"][0], _d["bin"][1])
	if _d.has("pond"):
		var pdct: Dictionary = _d["pond"]
		POND = { "pos": Vector2(pdct["pos"][0], pdct["pos"][1]), "r": float(pdct["r"]), "depth": float(pdct["depth"]), "water_y": float(pdct["water_y"]), "trough": Vector2(pdct["trough"][0], pdct["trough"][1]) }
	SIGNPOST = Vector2(_d["signpost"][0], _d["signpost"][1])
	LOG_SEAT = Vector3(_d["log_seat"][0], _d["log_seat"][1], -deg_to_rad(_d["log_seat"][2]))
	LANDMARK_OAK = Vector2(_d["landmark_oak"][0], _d["landmark_oak"][1])
	for f in _d["fence"]:
		var pts: Array = []
		for p in f:
			pts.append(Vector2(p[0], p[1]))
		FENCE.append(pts)
	TREES = _d["trees"]
	SHRUBS = _d["shrubs"]
	BORDER_TREES = _d.get("border_trees", [])
	VILLAGE = _d.get("village", [])
	FERNS = _d.get("ferns", [])
	LOGS = _d.get("logs", [])
	PLAYER_START = Vector2(_d["player_start"][0], _d["player_start"][1])
	var b: Array = _d["bounds"]
	BOUNDS = Rect2(b[0], b[1], b[2], b[3])
	for s in _d["barricades"]:
		BARRICADES.append({ "id": s["id"], "name": s["name"], "pos": Vector2(s["pos"][0], s["pos"][1]), "yaw": float(s["yaw"]), "segments": int(s["segments"]) })
	for k in _d["spawns"]:
		var pts: Array = []
		for p in _d["spawns"][k]:
			pts.append(Vector2(p[0], p[1]))
		SPAWNS[k] = pts

static func extent() -> Rect2:
	_ensure()
	return Rect2(_x0, _z0, _w - 1, _hh - 1)

static func _sample(x: float, z: float) -> float:
	var fx := clampf(x - _x0, 0.0, _w - 1.001)
	var fz := clampf(z - _z0, 0.0, _hh - 1.001)
	var i := int(fx); var j := int(fz)
	var tx := fx - i; var tz := fz - j
	var a := _h[j * _w + i]; var b := _h[j * _w + i + 1]
	var c := _h[(j + 1) * _w + i]; var d := _h[(j + 1) * _w + i + 1]
	return lerpf(lerpf(a, b, tx), lerpf(c, d, tx), tz)

# Match the two triangles of each 1 m terrain cell, rather than the bilinear
# height used for smooth placement. Ground overlays must follow the rendered surface.
static func surface_height(x: float, z: float) -> float:
	_ensure()
	if not extent().has_point(Vector2(x, z)):
		return ground_height(x, z)
	var fx := x - _x0
	var fz := z - _z0
	var i := mini(int(fx), _w - 2)
	var j := mini(int(fz), _hh - 2)
	var tx := fx - i
	var tz := fz - j
	var a := _h[j * _w + i]
	var b := _h[j * _w + i + 1]
	var c := _h[(j + 1) * _w + i]
	if tx + tz <= 1.0:
		return a + (b - a) * tx + (c - a) * tz
	var d := _h[(j + 1) * _w + i + 1]
	return d + (c - d) * (1.0 - tx) + (b - d) * (1.0 - tz)

# outside the playable extent the coarse 10 m surroundings raster (same DEM) takes over
static func _far(x: float, z: float) -> float:
	var fx := clampf((x - _skx0) / _skc, 0.0, _skw - 1.001)
	var fz := clampf((z - _skz0) / _skc, 0.0, _skh - 1.001)
	var i := int(fx); var j := int(fz)
	var tx := fx - i; var tz := fz - j
	var a := _sk[j * _skw + i]; var b := _sk[j * _skw + i + 1]
	var c := _sk[(j + 1) * _skw + i]; var d := _sk[(j + 1) * _skw + i + 1]
	return lerpf(lerpf(a, b, tx), lerpf(c, d, tx), tz)

static func ground_height(x: float, z: float) -> float:
	_ensure()
	var inx := x - _x0
	var inz := z - _z0
	if inx < 0.0 or inz < 0.0 or inx > _w - 1 or inz > _hh - 1:
		# blend from the fine grid to the coarse one over the last 20 m so the seam stays closed
		var out := maxf(maxf(-inx, -inz), maxf(inx - (_w - 1), inz - (_hh - 1)))
		var k := clampf(out / 20.0, 0.0, 1.0)
		return lerpf(_sample(x, z), _far(x, z), k)
	return _sample(x, z)

static func ground_pos(x: float, z: float) -> Vector3:
	return Vector3(x, ground_height(x, z), z)

static func ground_normal(x: float, z: float) -> Vector3:
	var e := 0.5
	var dx := (ground_height(x + e, z) - ground_height(x - e, z)) / (2.0 * e)
	var dz := (ground_height(x, z + e) - ground_height(x, z - e)) / (2.0 * e)
	return Vector3(-dx, 1.0, -dz).normalized()

# cover weights from ground.png: r = forest floor / leaf litter, g = meadow grass, b = gravel
static func cover(x: float, z: float) -> Color:
	_ensure()
	# Cover has a finer grid than heights; match the shader's texel centres.
	var i := clampi(roundi((x - _x0) * _ground.get_width() / _w), 0, _ground.get_width() - 1)
	var j := clampi(roundi((z - _z0) * _ground.get_height() / _hh), 0, _ground.get_height() - 1)
	return _ground.get_pixel(i, j)

static func leaf_weight(x: float, z: float) -> float:
	return cover(x, z).r

static func meadow_weight(x: float, z: float) -> float:
	return cover(x, z).g

static func gravel_weight(x: float, z: float) -> float:
	return cover(x, z).b

static func in_forest(x: float, z: float) -> bool:
	return cover(x, z).r > 0.6

static func dist_to_polyline(p: Vector2, pts: Array) -> float:
	var best := 1e9
	for i in pts.size() - 1:
		var a: Vector2 = pts[i]
		var b: Vector2 = pts[i + 1]
		var ab := b - a
		var t := clampf((p - a).dot(ab) / maxf(ab.length_squared(), 1e-6), 0.0, 1.0)
		best = minf(best, (a + ab * t).distance_to(p))
	return best

static func on_road(x: float, z: float, margin: float = 0.0) -> bool:
	_ensure()
	var p := Vector2(x, z)
	for r in ROADS:
		if dist_to_polyline(p, r["pts"]) < r["width"] / 2.0 + margin:
			return true
	return false

static func in_building(x: float, z: float, margin: float = 0.0) -> bool:
	_ensure()
	for b in BUILDINGS.values():
		var pos: Vector2 = b["pos"]
		var size: Vector2 = b["size"]
		var d := Vector2(x, z) - pos
		var yaw: float = -b["yaw"]
		var l := Vector2(d.x * cos(yaw) + d.y * sin(yaw), -d.x * sin(yaw) + d.y * cos(yaw))
		if absf(l.x) < size.x / 2.0 + margin and absf(l.y) < size.y / 2.0 + margin:
			return true
	return false

static func in_clearing(x: float, z: float) -> bool:
	_ensure()
	if not SMALL_CAMPSITE.is_empty() and Vector2(x, z).distance_to(SMALL_CAMPSITE.pos) < SMALL_CAMPSITE.radius:
		return true
	return Geometry2D.is_point_in_polygon(Vector2(x, z), CLEARING)

# Areas that must stay free of trees and shrubs
static func is_clear_zone(x: float, z: float) -> bool:
	if on_road(x, z, 2.0) or in_building(x, z, 2.5) or in_clearing(x, z):
		return true
	return Vector2(x, z).distance_to(FIRE) < 10.0
