"""Turn the local .env (EOS client credentials, never committed) into godot/eos.cfg for the editor and the export.

    python tools/eos_config.py            # write godot/eos.cfg, fail when a value is missing
    python tools/eos_config.py --check    # only report which values are present (no secrets printed)
    python tools/eos_config.py --optional # write what is there, exit 0 even without a .env (dev machines)

The game (scripts/online_lobby.gd) reads res://eos.cfg, which the export preset packs into RemZ.pck, so players
never need a .env. The client secret of a Peer2Peer client policy is meant to live inside the game client
(Epic's own guidance); keep it out of git, logs and screenshots all the same. Values are never printed here,
only their presence.
"""
import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV = ROOT / '.env'
OUT = ROOT / 'godot' / 'eos.cfg'
KEYS = {
    'EOS_PRODUCT_NAME': 'product_name',
    'EOS_PRODUCT_ID': 'product_id',
    'EOS_SANDBOX_ID': 'sandbox_id',
    'EOS_DEPLOYMENT_ID': 'deployment_id',
    'EOS_CLIENT_ID': 'client_id',
    'EOS_CLIENT_SECRET': 'client_secret',
}
OPTIONAL = {'EOS_PRODUCT_NAME': 'RemZ', 'EOS_PRODUCT_VERSION': ''}


def parse_env(text: str) -> dict:
    """KEY=value lines; comments, blank lines, `export KEY=`, single or double quotes and CRLF are accepted."""
    values = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        if line.startswith('export '):
            line = line[len('export '):].strip()
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        elif ' #' in value:
            value = value.split(' #', 1)[0].rstrip()
        if key:
            values[key] = value
    return values


def load_values() -> dict:
    values = dict(OPTIONAL)
    if ENV.exists():
        values.update(parse_env(ENV.read_text(encoding='utf-8')))
    for key in list(KEYS) + ['EOS_PRODUCT_VERSION']:
        if os.environ.get(key):
            values[key] = os.environ[key]
    return values


def missing(values: dict) -> list:
    return [key for key in KEYS if not values.get(key)]


def write_cfg(values: dict, version: str) -> None:
    lines = ['; Generated by tools/eos_config.py from the local .env - do not commit, do not edit.', '[eos]']
    for key, name in KEYS.items():
        lines.append('%s="%s"' % (name, values.get(key, '').replace('"', '')))
    lines.append('product_version="%s"' % version)
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='report presence only, write nothing')
    parser.add_argument('--optional', action='store_true', help='do not fail on a missing .env or value')
    parser.add_argument('--version', default='', help='product version reported to EOS (default: NetSession.BUILD)')
    args = parser.parse_args()
    values = load_values()
    absent = missing(values)
    for key in KEYS:
        print('%-20s %s' % (key, 'missing' if key in absent else 'present'))
    version = args.version or values.get('EOS_PRODUCT_VERSION') or _build_constant()
    if args.check:
        return 1 if absent else 0
    if absent and not args.optional:
        print('eos_config: %s missing in %s - the online lobby cannot be built without them' % (', '.join(absent), ENV), file=sys.stderr)
        return 1
    write_cfg(values, version)
    print('wrote', OUT.relative_to(ROOT), '(complete)' if not absent else '(incomplete: %s)' % ', '.join(absent))
    return 0


def _build_constant() -> str:
    source = (ROOT / 'godot' / 'scripts' / 'net_session.gd').read_text(encoding='utf-8')
    for line in source.splitlines():
        if line.startswith('const BUILD :='):
            return line.split('"')[1]
    return 'dev'


if __name__ == '__main__':
    raise SystemExit(main())
